version: 2.1

workflows:
  version: 2

  build:
    jobs:
      - build-site:
          filters:
            branches:
              ignore: gh-pages


build_jekyll: &build_jekyll
    name: Jekyll Build
    command: |
        if [ -z "$CIRCLECI_TRIGGER" ]; then
            echo "Building RSE Roles for Preview"
            cp ~/repo/.circleci/circle_urls.sh ~/repo/circle_urls.sh
            cd ~/repo
            chmod u+x circle_urls.sh
            bash circle_urls.sh              
            bundle exec jekyll build
        else
            echo "Nightly build detected, preview not needed."
        fi

jobs:
  build-site:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
          - rubygems-v1
      - run:
          name: Bundle Install
          command: |
              cd ~/repo
              bundle check || bundle install
      - save_cache:
          key: rubygems-v1
          paths:
            - vendor/bundle
      - run: *build_jekyll
      - store_artifacts:
          path: ~/repo/_site
          destination: rse-roles
